### PR TITLE
add as much button support as we can to the RC71 (ROG Ally)

### PR DESCRIPTION
**Pull request by ktemkin**
Just a quick patch I made for myself (and a quick fix for custom commands using the M2 button) -- thought I'd send this upstream in case it's helpful. :)

### CODE REVIEW

**Comment by seerge** [comment]
@ktemkin hello, thanks for contribution, that can work I guess :)

**Comment by k-trahan** [comment]
I don't think this is quite right.

"m1" is still considered the volume down button on the Ally and not the back paddles. "m2" is still volume up and by hiding the label and combo box, you lose the ability to adjust the volume up hotkey.

At a minimum, I think further work is needed in Input/InputDispatcher.cs around line 224 for special handling of RC71 hardware. Also need additional labels and inputs for the two volume buttons.

**Comment by seerge** [comment]
@k-trahan did you update to 0.105?

**Comment by k-trahan** [comment]
> @k-trahan did you update to 0.105?

Yes, this is after updating to v0.105.

You can observe some of this by using 0.103, changing the volume down hotkey, changing back to 0.105 and noticing that your hotkey you just set is defined in "Back Paddles".

**Comment by ktemkin** [comment]
I see what's happening -- the hooks are still there for the Vol+/Vol- translation into M1/M2 in a code path targeted for other devices.

I'll have a fix in a sec. >.<

**Comment by seerge** [comment]
@k-trahan @ktemkin 
[GHelper.zip](https://github.com/seerge/g-helper/files/12264072/GHelper.zip)

This one should skip binding to volume keys :) + i have reorganized some stuff inside

**Comment by ktemkin** [comment]
https://github.com/seerge/g-helper/pull/1003 <-- I threw this PR up as a quick fix, but if you have a better version than my quick two-line tweak, feel free to just close it. :)

**Comment by k-trahan** [comment]
Tested the build above and it looks good to me, Appreciate you both!

**Comment by seerge** [comment]
@ktemkin I'm sorry to brutally intrude into your PR, but i have made some adjustments (in main branch). So now Ctrl Center + Paddle has own param name (for config) + will have default action as nothing (-----).

As by just reusing g-helpers M1, M3 it would just bind volume-down and mic-mute to it otherwise, which may confuse people who just installed it

I didn't touch Ctrl+M1/M2 and Shift + M1/M2 bindings, as (theoretically), why not to keep them for ally? and control brightness with Ctrl + volume keys? :))) i personally missed that on my ally

Build with updates : 
[GHelper.zip](https://github.com/seerge/g-helper/files/12264232/GHelper.zip)

**Comment by k-trahan** [comment]
> @ktemkin I'm sorry to brutally intrude into your PR, but i have made some adjustments (in main branch). So now Ctrl Center + Paddle has own param name (for config) + will have default action as nothing (-----).
> 
> As by just reusing g-helpers M1, M3 it would just bind volume-down and mic-mute to it otherwise, which may confuse people who just installed it
> 
> I didn't touch Ctrl+M1/M2 and Shift + M1/M2 bindings, as (theoretically), why not to keep them for ally? and control brightness with Ctrl + volume keys? :))) i personally missed that on my ally
> 
> Build with updates **: [GHelper.zip](https://github.com/seerge/g-helper/files/12264265/GHelper.zip)
> 
> I hope it works (i have returned my Ally back to the store, so can't really test anymore)

This build works, too, and I like the change with the default action being "-----".

I also **really** like the idea of adjusting brightness with CTRL + M1/Vol. Down and CTRL + M2/Vol. Up. I'm probably overlooking something obvious but how can I set these hotkeys? On my Ally, the only Key Bindings I have now are Ctrl Center, ROG, and Back Paddles.

(Also bummed that you no longer have your Ally, @seerge!)

**Comment by seerge** [comment]
@k-trahan i think you can bind some of gamepad keys (like RB or RT to be control or shift?) You can also try to bind back-paddle to be Ctrl (via custom hotkeys in g-helper itself), but main problem here - is app gets only CLICK event for padddle/ctrl center/rog (so it doesn't know if button is still pressed) and therefore it can't emit holding Control, only clicking it in turn.

**Comment by k-trahan** [comment]
Makes sense, thanks so much for the explanation, @seerge.

**Pull request merged**
