### PR TITLE
fix: ulterior fixes from #1636

### PR DESCRIPTION
**Pull request by Constrat**
Ulterior fixes related to #1636 brought up for 15 inches models.

### CODE REVIEW

**Comment by seerge** [comment]
@Constrat hm this pr conflicts with last one you did :)

**Comment by Constrat** [comment]
Yeah, it was pretty much expected, as I change some small things. (GitHub doesn't like them :P)

**Comment by Constrat** [comment]
Ops, I still had a commit to push with a little style and LIDL from zone 0 to zone 2 as it makes more sense looking at this: 
G533_US_1100

**Comment by Constrat** [comment]
If you want to, just replace this:
https://github.com/seerge/g-helper/blob/93d639fc6fce58025a35b15d958e2d5089da467c/app/USB/Aura.cs#L402-L406
With this:
```cpp
             0,    0,    0,    0,                1,                1,    2,    2,          2,    2,    2,    3,          3,    3,    3,
        /* LB1   LB1   LB3                                                                                             LB4   LB5   LB6   */
             5,    5,    4,                                                                                              6,    7,    7,
        /* KSTN  LOGO  LIDL  LIDR  */
             3,    0,    2,    3,

```

**Comment by Constrat** [comment]
Wait how did a `=` go in the code? 
@seerge I think it might be better to revert

**Comment by seerge** [comment]
@Constrat I have already merged + just pushed tweaks over that (i rearranged zones back for models w/o numpad)

@Kowken can you check if this build looks ok for you ?
[GHelper.zip](https://github.com/seerge/g-helper/files/13449313/GHelper.zip)

**Comment by Kowken** [comment]
> @Constrat I have already merged + just pushed tweaks over that (i rearranged zones back for models w/o numpad)
> 
> 
> 
> @Kowken can you check if this build looks ok for you ?
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/13449313/GHelper.zip)
> 
> 
> 
> 

Looks fine to meimage

**Comment by seerge** [comment]
@Kowken bingo.

I assume my latest "tweaks" don't break backlight on the numpad version of keyboard @Constrat ?

If so - thank you both

**Comment by Constrat** [comment]
> @Kowken bingo.
> 
> I assume my latest "tweaks" don't break backlight on the numpad version of keyboard @Constrat ?
> 
> If so - thank you both

Yep, just checked, everything working as expected, the zones are 5-width in my case. Maybe the regex for the model should be any 17 inch? Instead of just G713R? (If the asus nomeclature stays the same, usually 17 inches have numpads)

**Pull request merged**
