### PR TITLE
Spanish translation fix for "Updates" + more

### PR DESCRIPTION
**Pull request by marcelomijas**
Now the translation will fit the "Updates" button.

### CODE REVIEW

**Comment by seerge** [comment]
@marcelomijas I have just added start/stop section for asus services (under Extra), does it make sense to translate them as well ? Thanks

**Comment by marcelomijas** [comment]
@seerge yes. I didn't see that. I'm working on it. I'll update the pull request. Thanks!

**Comment by marcelomijas** [comment]
Done @seerge ! 👍🏼

**Comment by seerge** [comment]
Thanks!

**Pull request merged**
