### PR TITLE
Anime Matrix tweaks

### PR DESCRIPTION
**Pull request by seerge**
Fixed matrix rendering for G14 2020/2021 and added new Clock design :)

### CODE REVIEW

**Comment by seerge** [comment]
@IceStormNG hello :)

Thanks to your last PR or Matrix on M16 I have finally figured out and properly fixed matrix for G14 2020/2021 (it's the worst version of it)

I have also improved clock mode rendering (including native matrix font) and added date to it.

Can you check if it looks ok on your M16 screen ? and if not - set correct value here for your sizes ?
https://github.com/seerge/g-helper/blob/c791421c3e328d27361a055b834605681663c652/app/AnimeMatrix/AnimeMatrixDevice.cs#L131

**Comment by seerge** [comment]
@IceStormNG i didn't really center it , but tried to fit into smallest version of matrix on G14 2021 (it has least amount of leds)

**Comment by IceStormNG** [comment]
IMG_1765

This is how it looks with the current state without any change by me

**Comment by seerge** [comment]
@IceStormNG i think it's fine as is then

I may try to do "proper" centering later, but then I need to calculate actual length of the diagonal (taking into account the height of the text itself as well)

But for now it will work :)

**Pull request merged**
