### PR TITLE
Support for ROG Keris P509

### PR DESCRIPTION
**Pull request by IceStormNG**
Support for ROG Keris P509 (the regular wired variant). #2517

### CODE REVIEW

**Comment by seerge** [comment]
@IceStormNG thanks a lot!

**Comment by BladeJoe** [comment]
hey there despite my laptop not support the custom fan curve,i found other (https://github.com/chiputillo) software that can override, you guys could merge these projects and would help many people those laptops thermal throttling

**Comment by seerge** [comment]
@BladeJoe how is it related to ROG Keris ?

If you need custom fan control you can just use https://github.com/seerge/g-helper/discussions/2272

**Comment by BladeJoe** [comment]
> @BladeJoe how is it related to ROG Keris ?
> 
> If you need custom fan control you can just use #2272

sorry my bad, downlodaded g-helper latest version and didnt know there was experimental releases. although had to open issue(was looking for discussion,Still not very familiar with github and learning)

**Pull request merged**
