### PR TITLE
Updated README.md for better readability.

### PR DESCRIPTION
**Pull request by kindaLakshay**
Punctuation and grammar changes without changing the formatting.

### CODE REVIEW

**Review by Constrat — APPROVED** [review]

**Review by Constrat — APPROVED** [review]
LGTM.
Looks more cleaner and tidier. (Keeping the format consistent!)

**Comment by thepriyamkalra** [comment]
May be a good idea to add the stripe links to the "support project" section since PayPal doesn't work in some countries (for example, I think its supposed to work in India but due to some policy it doesn't always work now)

**Comment by goodolLakshay** [comment]
> May be a good idea to add the stripe links to the "support project" section since PayPal doesn't work in some countries (for example, I think its supposed to work in India but due to some policy it doesn't always work now)

Adding Stripe links is a good idea, but since I am new to the Open Source community, I do not wish to mess with anything financial. I just read the readme.md and improved the readability and correctness of the documentation, which will help newcomers better understand this project's usage and functionality. My last pull request got rejected as I accidentally changed the apostrophes, which would mess with the json structure. Then I made more changes, and Seerge added more, so I had to do it again. Oof :)

**Comment by goodolLakshay** [comment]
Dear @seerge, As a dedicated contributor, receiving feedback is crucial to my motivation and continued involvement in the project.
I understand that, as the project owner, you have other commitments. However, I cannot keep resolving conflicts in files every time you make commits while _moving_ over my suggested changes. I genuinely appreciate your work and try to contribute in any meaningful way possible. I would really appreciate you communicating.

**Comment by seerge** [comment]
@goodolLakshay hello, thanks for the effort :) But I'm currently actively editing my readme, and trying to simplify / optimize it, so I don't think that that this is the best time for fixing articles or changing some words to British English from American English  :)

**Pull request closed without merging**
