### PR TITLE
(PT-BR) Translation update (Strings.pt-br.resx)

### PR DESCRIPTION
**Pull request by weslleykawan**
Added/updated strings:

```
    <data name="VolumeDown" xml:space="preserve">
    <value>Abaixar o volume</value>
  </data>

  <data name="VolumeUp" xml:space="preserve">
    <value>Aumentar o volume</value>
  </data>

    <data name="VolumeMute" xml:space="preserve">
    <value>Silenciar microfone</value>
  </data>

  <data name="WindowTop" xml:space="preserve">
    <value>Manter a janela do aplicativo sempre no topo</value>
  </data>

   <data name="Updates" xml:space="preserve">
    <value>Atualizações</value>
  </data>

    <data name="FnLock" xml:space="preserve">
    <value>Processar teclas de atalho Fn+F sem pressionar Fn</value>
  </data>

   <data name="KillGpuApps" xml:space="preserve">
    <value>Parar todos os aplicativos que usam a GPU ao alternar para o modo Eco</value>
  </data>

  <data name="Boot" xml:space="preserve">
    <value>Ao ligar</value>
  </data>

  <data name="Brightness" xml:space="preserve">
    <value>Nível do brilho</value>
  </data>

  <data name="BacklightTimeout" xml:space="preserve">
    <value>Tempo limite da iluminação na bateria (em segundos)</value>
  </data>

    <data name="BacklightTimeoutPlugged" xml:space="preserve">
    <value>Tempo limite da iluminação carregando (0 - sempre ligado)</value>
  </data>

  <data name="LaptopBacklight" xml:space="preserve">
    <value>Configurações de iluminação</value>
  </data>

  <data name="ApplyWindowsPowerPlan" xml:space="preserve">
    <value>Ajuste automático dos modos de energia do Windows</value>
  </data>

    <data name="AsusServicesRunning" xml:space="preserve">
    <value>Serviços da Asus em execução</value>
  </data>

<data name="Start" xml:space="preserve">
    <value>Iniciar</value>
  </data>
  <data name="StartingServices" xml:space="preserve">
    <value>Iniciando os serviços</value>
  </data>
  <data name="StartupError" xml:space="preserve">
    <value>Erro de inicialização</value>
  </data>
  <data name="Stop" xml:space="preserve">
    <value>Parar</value>
  </data>
  <data name="StoppingServices" xml:space="preserve">
    <value>Parando os serviços</value>
  </data>
```

If you can offer me a test version with these modifications, I'll run the tests to see if everything is working.

### CODE REVIEW

**Comment by seerge** [comment]
@weslleykawan hello, thanks for contribution, are those translations final?

**Comment by weslleykawan** [comment]
> 

Yes, they are final. We can test?

**Comment by seerge** [comment]
@weslleykawan sure
[GHelper.zip](https://github.com/seerge/g-helper/files/11736281/GHelper.zip)

**Comment by weslleykawan** [comment]
Now the translation is much better and more coherent into Brazilian Portuguese.
However, I identified an error and here is the solution:

To replace:

```
    <data name="VolumeMute" xml:space="preserve">
    <value>Silenciar microfone</value>
  </data>
```

By:

```
    <data name="VolumeMute" xml:space="preserve">
    <value>Mudo</value>
  </data>
```


And add the string:

```
    <data name="MuteMic" xml:space="preserve">
    <value>Desligar microfone</value>
  </data>
```

PS: The string "PPT Experimental" does not appear.
Try adding:

```
  <data name="PPTExperimental" xml:space="preserve">
    <value>Limitações de Energia é uma funcionalidade experimental. Use com cuidado.</value>
  </data>
```

If possible, please offer a version so that I can verify that it is 100% functional.

**Comment by weslleykawan** [comment]
> @weslleykawan sure
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/11736304/GHelper.zip)

Only that remains, the rest is working as expected. ✅

**Pull request merged**
