### PR TITLE
Improve Chinese translation

### PR DESCRIPTION
**Pull request by lswlc33**

### CODE REVIEW

**Comment by seerge** [comment]
@lswlc33 oke, thanks. is it final? (so i can merge)

**Comment by seerge** [comment]
@lswlc33 if you want - you can also make a copy and translate https://github.com/seerge/g-helper/blob/main/docs/README.md :)

**Comment by lswlc33** [comment]
> @lswlc33 oke, thanks. is it final? (so i can merge)

yes

**Comment by seerge** [comment]
@sklynic sure, i can merge

**Pull request merged**
