### PR TITLE
[Feature, Draft Version] Dark mode

### PR DESCRIPTION
**Pull request by astronaut701**
So, I've been wanting a dark mode for this for a bit now. However, my lack of knowledge on how to properly implement a dark mode is shooting me in the back here.

Right off the bat, this code is *not* ready to be merged as it stands, hence why it's a draft.

There's a few issues (listed in severity from my perspective) at hand, namely:

- How can I detect whether the user has Windows set to light/dark/auto mode and update the UI accordingly? (Or would a button be preferred for this task instead?) 

- The taskbar is still white, and I'm not sure how to change that at the moment. (Not the end of the world, but still.)

- The icons are dark, but that's easily fixed by inverting the colors, and using the inverted icons while dark mode is active.

Despite all that, here's how dark mode (from what I've cooked up so far) looks!

Dark-mode

### CODE REVIEW

**Comment by astronaut701** [comment]
Oh, and feedback on this would be appreciated!

**Comment by seerge** [comment]
Hello, that's a good start ! :) but we will need it to be fully themed then (including title bar, icons, borders, etc)

**Comment by seerge** [comment]
And I would investigate what is the proper way to do themes on windows tbh (instead of just recoloring each individual element).It should be some native support ... I'm not really familiar with that tbh :)

**Comment by astronaut701** [comment]
> And I would investigate what is the proper way to do themes on windows tbh (instead of just recoloring each individual element).It should be some native support ... I'm not really familiar with that tbh :)

I *think* that's a limitation of Windows Forms, but don't quote me on that.

**Comment by astronaut701** [comment]
WinUI would make tackling this issue easier, as it just flat out tells you the current theme when you ask for it and allows you to take action accordingly. It also allwos you to make the taskbar dark from the get-go. Only issue is that well... it'd require quite the swap from Windows Forms to WinUI 3.

I'll keep digging into doing this properly once I get a better chance later.

- Info about WinUI 3
https://microsoft.github.io/microsoft-ui-xaml/about.html

- Docs covering Dark Mode stuff for Win32 apps
https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/apply-windows-themes

**Comment by seerge** [comment]
Oke, seems like whole UI needs to be redone, mb we can get by with just a recoloring :)

**Comment by astronaut701** [comment]
Update - I've managed to detect which theme Windows is set to, and change stuff accordingly, however, in solving one problem, I've created another... how to detect when the user change's theme and adjust the color scheme in G-Helper to match.

(Note - I haven't pushed the commit with my changes to my branch yet, as I'm working on that issue. I'm also trying to figure how to make the taskbar dark. I may end up telling the Windows API to do that.)

**Comment by astronaut701** [comment]
Screenshot 2023-02-21 211724

Here's my last update from me for tonight. All that's pretty much left is to work out how to detect a change in theme while G-Helper is running.

**Comment by astronaut701** [comment]
Side note - I can't really test how Ultimate mode looks right now under dark mode, as my ASUS G15 from 2021 lacks a MUX switch. (I could mess around to allow to me to trigger the UI, but not the MUX switch itself, but I'm out of time for tonight.) Would appreciate it if someone could test this.

**Comment by astronaut701** [comment]
Hey @seerge, at this point, I'm not really liking how I'm implementing dark mode for G-Helper. Not only do I have to import two DLLs to pull off dark mode theme detection and making the taskbar dark, but I'm having manually go in and tell each element to change to a dark color. Hell, I haven't even gone into figuring out how to detect a theme change while stuff is running yet. Any pointers or thoughts?

**Comment by astronaut701** [comment]
Oh, and I have updated the code on my end (still need to push a commit though...) to work with the new fan with fan curves, but after all this mess just to get a dark mode theme going, it's making me step back and reconsider how I'm pulling this off.

**Comment by astronaut701** [comment]
Oops, hit the wrong button when adding the new code that resolve the conflict from the change in Settings.cs

Fixed now.

**Comment by astronaut701** [comment]
Still stuck on changing theme along with a theme change in Windows while G-Helper is running, but I've brought my branch up to update with the fan curves UI addition now.

**Comment by astronaut701** [comment]
image
 
 Oh, and here's how the dark mode looks on the fan curve UI.

**Comment by astronaut701** [comment]
Shoot... well I forgot to make the chart background not white... 😵‍💫 Time to go fix that.

**Comment by astronaut701** [comment]
image

Much better.

**Comment by seerge** [comment]
Cool, I will test it a bit later :)

**Comment by astronaut701** [comment]
Hey, I thought that I'd leave a message to set you know @seerge that I'm still working on dark mode, I've just been busy with my classes for two weeks now, as stuff has ramped up now and I've had less free time on my hands.

**Comment by seerge** [comment]
No worries, great that it's moving :) I have extended UI in the meantime (for new functionalities), so now could be a good time to finally recolor it all together

**Comment by astronaut701** [comment]
So, I finally have an update. I've managed to get the light and dark themes to switch in response to what its set to in Windows. I haven't pushed the changes, as I need to update the code on my end to work with the current version, and while the way (as previously discussed) of manual setting everything dark/light isn't pretty, it does work. I should be able to get everything together by tomorrow and potentially put this pull request up for review finally. 😄

**Comment by HamzaYslmn** [comment]
I support the dark mode <3. Just sayin :D

**Comment by astronaut701** [comment]
I have another update for you all before I call it another night. I've managed to make the code work between updates now. It'll adjust depending on UI changes. (Note - It cannot compensate for icon changes right now, however. I'll look into whether I can just tell Windows forms to invert icon colors, but we'll see.) I would push it to my repo, but I just want to get to bed right now...
(And yes, I'm aware of the dropdown being white, that's something else I need to get around to doing.)

image

**Comment by HamzaYslmn** [comment]
ı add pull request for the dark mode icons

**Comment by HamzaYslmn** [comment]
day-mode
icons8-charging-battery-white-48
icons8-fan-head-white-96
icons8-keyboard-white-48
icons8-laptop-white-48
icons8-matrix-desktop-white-48
icons8-processor-white-96
icons8-speed-white-48
icons8-speed-white-96
icons8-video-card-white-48
dark-mode

**Comment by astronaut701** [comment]
> pure white is not good for the dark mode. I use 250-250-250 rgb.

Noted. 👍

**Comment by seerge** [comment]
I have already implemented it :)

**Comment by HamzaYslmn** [comment]
We really need the dark theme. Large white panel is very eye catching on night.

**Comment by astronaut701** [comment]
> I have already implemented it :)

Alrighty, I'll go ahead and close this request then! Thanks for getting back to me on that.

**Comment by seerge** [comment]
Yeah, anyway default UI controls is a pain ... i had to recreate custom combo and button to overcome dark theme quirks, and it still doesn't look as I would want it to :D

**Comment by HamzaYslmn** [comment]
rgba(28,28,28,255)
#1c1c1c

Windows gray(dark) theme color

**Comment by astronaut701** [comment]
Yeah, I was about to get into the mess of getting the combo box to work. Anyhow, I see that it's set to dark mode all the time. Probably not an issue, but something I noticed.

**Comment by seerge** [comment]
@astronaut701 for me it does, what windows version do you have  ?

**Comment by astronaut701** [comment]
Windows 22H2, build 22621.1413

**Comment by HamzaYslmn** [comment]
I think dark mode always best option. It just needs a little more contrast adjustment, slightly bolder font. And ready to use.

**Comment by astronaut701** [comment]
Correct theme at launch, doesn't change when app is running.

**Comment by HamzaYslmn** [comment]
> Correct theme at launch, doesn't change when app is running.

Same

**Comment by astronaut701** [comment]
> I think dark mode always best option. It just needs a little more contrast adjustment, slightly bolder font. And ready to use.

I mostly mentioned the lack of change as you'll have that one person who prefers the light theme, and also people who run their laptop to swap themes over the course of a day.

**Comment by seerge** [comment]
@astronaut701 strange,  
``SystemEvents.UserPreferenceChanged += OnUserPreferenceChanged; `` is there
could this be your case https://github.com/microsoft/WindowsAppSDK/issues/3158 ?

**Comment by astronaut701** [comment]
> @astronaut701 strange, `SystemEvents.UserPreferenceChanged += OnUserPreferenceChanged; ` is there could this be your case [microsoft/WindowsAppSDK#3158](https://github.com/microsoft/WindowsAppSDK/issues/3158) ?
> 
> Can you try to catch with a debugger on your computer if event is fired ?

Give me a moment and I'll see...

**Comment by HamzaYslmn** [comment]
> I mostly mentioned the lack of change as you'll have that one person who prefers the light theme, and also people who run their laptop to swap themes over the course of a day.

Yes, the light theme is also needed, I just think that the dark theme fits everywhere and in all circumstances. Yes Black and White theme fits everywhere. But when it's night, the light theme starts to burn the eyes :D

**Comment by astronaut701** [comment]
No event fires on my end... @HamzaYslmn, how about your end?

**Comment by astronaut701** [comment]
As an aside, the way I pulled off changing theme was something like this...

```
            //Listen for system event indicating a change in theme
            SystemEvents.UserPreferenceChanged += new
                 UserPreferenceChangedEventHandler(SystemEvents_UserPreferenceChanged);
            
            //Execute code again in response to a theme change (Probably could be done cleaner, but for now it'll do.)
            void SystemEvents_UserPreferenceChanged(object sender, UserPreferenceChangedEventArgs e)
            {
            //run function, code, etc here....
            }
```
It's pretty similar, hence why I'm scratching my ahead as to why your method isn't working on my end.

**Comment by HamzaYslmn** [comment]
image

It changes but in open theme mode it gives an error and gets stuck.

**Comment by astronaut701** [comment]
Huh, odd.

**Comment by HamzaYslmn** [comment]
now, ı restart my pc for dark mode 💀

**Comment by seerge** [comment]
@astronaut701 - can you try 
[GHelper.zip](https://github.com/seerge/g-helper/files/11021312/GHelper.zip)

**Comment by astronaut701** [comment]
Standby...

**Comment by astronaut701** [comment]
Nope. The icons are getting smaller every time I change theme oddly enough.

**Comment by HamzaYslmn** [comment]
image
nope... still stuck in light mode

**Comment by seerge** [comment]
@HamzaYslmn not sure what are you trying to achieve, but based on your screenshot you are running a wrong version even.

**Comment by seerge** [comment]
@astronaut701 that's a side effect of icon resizing, but that means event is triggered actually.

**Comment by HamzaYslmn** [comment]
image
sorry about that, wrong file...

**Comment by astronaut701** [comment]
> @astronaut701 that's a side effect of icon resizing, but that means event is triggered actually.

Okay, so something is working, it just isn't changing the colors.

**Comment by HamzaYslmn** [comment]
image
BTW when I open the app, it glows like hell.

**Comment by seerge** [comment]
@astronaut701 can you try this one 
[GHelper.zip](https://github.com/seerge/g-helper/files/11021485/GHelper.zip)

**Comment by HamzaYslmn** [comment]
image
nothing changed

**Comment by HamzaYslmn** [comment]
image
after compile

**Comment by seerge** [comment]
@astronaut701 - another "alternative" approach : 
[GHelper.zip](https://github.com/seerge/g-helper/files/11021651/GHelper.zip)

**Comment by astronaut701** [comment]
Works perfectly now!

**Comment by seerge** [comment]
@astronaut701 , great, thanks for testing . I just replaced v0.33 with a fixed version :)

**Comment by astronaut701** [comment]
Okay... there's an issue with swapping somewhere, but I'm out of time to test.

**Comment by astronaut701** [comment]
When Fan UI is open, light to dark does not seem to work.

**Comment by astronaut701** [comment]
Keyboard settings UI also has this issue as well as. Going from light to dark while it's open also breaks it.

**Comment by astronaut701** [comment]
> [GHelper.zip](https://github.com/seerge/g-helper/files/11022510/GHelper.zip) @astronaut701 I have added a 0.5sec delay before reading theme, may be that will help

@seerge That seems to work most of the time. It occasionally still fails to swap (on either extra UI) but switching a few more times gets it going again. I would debug it, but I'm out of battery sadly.

**Pull request closed without merging**
