### PR TITLE
fix: z13 rear window light #930 #843

### LINKED ISSUE #930: [bug] Flow Z13 Rear Window Lighting break since 0.97 update.
Follow the #843, I test all release from 0.89 to 0.100, and located .97 will make `Rear Window Lighting` break on ghelper.exe start, but can be re-enabled in Armoury Crate.

I'm trying to find commits that contain this bug, I can physically access to the device, and I'm also SoC software developer so if anything I can help I'll try my best ;)

**Describe the bug**
Z13 Rear Window Lighting (hereinafter called *RWL*) break since 0.97 update.

**Clear scenario to Reproduce**
1. Turn on RWL in Armoury Crate.
2. run 0.96, it okey nothing change.
3. run 0.97 RWL will turn off.

**Expected behavior**
Like 0.96, runing ghelper won't turn off RWL.

**App Logs**
[97_log.txt](https://github.com/seerge/g-helper/files/12208545/97_log.txt)
[96_log.txt](https://github.com/seerge/g-helper/files/12208546/96_log.txt)
```git diff
# git diff 096.log 097.log
+ 2023/7/30 13:06:50: TL134ADXP01-0:DISPLAYCONFIG_OUTPUT_TECHNOLOGY_INTERNAL: \\.\DISPLAY1
+ 2023/7/30 13:06:52: USB-KB 0x18C6:5D-BD-01-FF-1E-0F
+ 2023/7/30 13:06:52: Auto:5D-BA-C5-C4-03
+ 2023/7/30 13:06:52: USB-KB 0x1A30:5D-BD-01-FF-1E-0F
- 2023/7/30 13:06:30: Auto:5D-BA-C5-C4-03
```

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Laptop model: z13

**Asus software**
- Armoury crate (or it's services installed)
- Only `AsusOptimization.exe` except Armoury Crate stuffs.

----
edit:
most suspicious commit https://github.com/seerge/g-helper/commit/e5f0d77d05f0388b5449f7361897a60aaf54a4c5

### PR DESCRIPTION
**Pull request by rainbowflesh**
Close #930

Plz other users with z13 devices help to verify this change.

@d0j1a1701

[net7.0-windows.zip](https://github.com/seerge/g-helper/files/12208609/net7.0-windows.zip)

### CODE REVIEW

**Comment by seerge** [comment]
@rainbowflesh hello, why don't you just add ``"skip_aura":1,`` to config.json to achieve same result ? I will respond to your main issue about proper implementation of backlight there.

**Comment by rainbowflesh** [comment]
> @rainbowflesh hello, why don't you just add `"skip_aura":1,` to config.json to achieve same result ? I will respond to your main issue about proper implementation of backlight there.

Thats work! And forgive me that I debug with git checkout 0.97 tag, didn't notice there already have an option to disable it `by config.json` in newer release 😵

**Comment by d0j1a1701** [comment]
It works. Thanks!

**Comment by seerge** [comment]
@d0j1a1701 last v0.103 has a dedicated support for a led light, so there is no need in setting any configurations

**Pull request closed without merging**
