### PR TITLE
Add Power Limit for ROG Ally & fix Designer

### PR DESCRIPTION
**Pull request by patrickpielarski**
- add Power Limit for ROG Ally 
- fix Designer for Forms not working in Visual Studio

### CODE REVIEW

**Comment by seerge** [comment]
@patrickpielarski hello, but Ally supports 43W+ even :) higher values most probably won't have much effect (as there is a hard limit in BIOS)

 I can add a limit to 43W or 50W if you want

**Comment by patrickpielarski** [comment]
@seerge  Hi, didn't know about it being able to go higher than 30W. But with 43W the CPU voltage should be dropped also? If not the Ally will throttle itself back to 30W after 2 minutes according to:
https://www.reddit.com/r/ROGAlly/comments/14iqv30/4243w_turbo_mode_gpu_throttle/
https://www.reddit.com/r/ROGAlly/comments/14v5h88/43w_rog_ally_gives_much_smoother_experience/

But a value lower than 150 like 43 or 50 would be appreciated. Just don't know if it really works.

**Comment by seerge** [comment]
@patrickpielarski Ally has sustained, long and short boosts.

It can go up to 43W officially even. So I think 50W would be ok (mb they will unlock something in future via BIOS)

I have added that https://github.com/seerge/g-helper/commit/3652e4d0ffce2b96c00f64b14d29eb6011d60000

**Comment by patrickpielarski** [comment]
> @patrickpielarski Ally has sustained, long and short boosts.
> 
> It can go up to 43W officially even. So I think 50W would be ok (mb they will unlock something in future via BIOS)
> 
> I have added that [3652e4d](https://github.com/seerge/g-helper/commit/3652e4d0ffce2b96c00f64b14d29eb6011d60000)

@seerge Thanks! The other change in my branch was putting the struct away from top of the file so Visual Studio opens the Designers again for the Forms.

**Comment by patrickpielarski** [comment]
> @patrickpielarski hmm, my studio (latest version) doesn't have problems with that, but I moved struct inside form, so it should be ok now
> 
> [584755e](https://github.com/seerge/g-helper/commit/584755ea93aca8e51a03c5f51608e25eb2eaceea) :)

Thanks. Just installed 2022 Community Edition on the Ally to test it and it wouldn't open the designers because of that one struct. Appreciated!

**Comment by seerge** [comment]
Do you mean it still doesn't work for you? :)

**Comment by patrickpielarski** [comment]
No it works now. I was just claryfying that it wasn't working before. Thanks

**Pull request closed without merging**
