### PR TITLE
fix: Ambient Mode for 17 inch keyboards

### PR DESCRIPTION
**Pull request by Constrat**

### CODE REVIEW

**Comment by seerge** [comment]
@Constrat great, thanks !

@Kowken can you check on your device w/o numpad if this build still looks ok ?

[GHelper.zip](https://github.com/seerge/g-helper/files/13447475/GHelper.zip)

**Comment by Constrat** [comment]
I tried making it the most scalable possible, implementing both the "older" values you had and the "new" values from the .csv of my 17'' model that we used in the ORGB project 17 inch adaptation.

**Comment by Kowken** [comment]
> @Constrat great, thanks !
> 
> 
> 
> @Kowken can you check on your device w/o numpad if this build still looks ok ?
> 
> 
> 
> [GHelper.zip](https://github.com/seerge/g-helper/files/13447475/GHelper.zip)
> 
> 

Not gonna lie, it looks worse than before.
image

**Comment by Constrat** [comment]
It's a "zone" issue. We should find a way to differentiate between layout sizes (like inORGB)

**Comment by seerge** [comment]
@Constrat or you have accidentally mixed some numbers in the change? :)

**Comment by Constrat** [comment]
> @Constrat or you have accidentally mixed some numbers in the change? :)

I'll check (maybe I left them when I was testing the zone 6 and 7 xD)

**Comment by Kowken** [comment]
> > @Constrat great, thanks !
> > 
> > 
> > 
> > @Kowken can you check on your device w/o numpad if this build still looks ok ?
> > 
> > 
> > 
> > [GHelper.zip](https://github.com/seerge/g-helper/files/13447475/GHelper.zip)
> > 
> > 
> 
> Not gonna lie, it looks worse than before.
> image
> 
> EDIT: Hold on actually, I'll send more examples because I may be mistaken

imageimage

**Comment by Constrat** [comment]
Issue identified, dw. I can create a new PR.

**Comment by Constrat** [comment]
@Kowken what's the not lit up key? Next to the Right Shift? Is it next?

**Comment by Kowken** [comment]
> @Kowken what's the not lit up key? Next to the Right Shift? Is it next?
> 
> Seems like it correct?

Regarding ambient, all keys light up but it more a matter of how they light up, the 0.134 release made 4 zones but now there are the numkeys 4,5, 6 and 7 that lights up differently from the rest and from each other, also the skip button never lights up.imageimage

**Comment by Constrat** [comment]
@Kowken It's the fourth time I said this. This was identified, it was a mistake on my end. What I need now is something else xD

**Comment by Kowken** [comment]
> @Kowken It's the fourth time I said this. This was identified, it was a mistake on my end. What I need now is something else xD

If you are referring to both issues I mentioned (numkeys and skip) then all my apologies. The shift button look correct though, I'm sure what you are looking for.

**Comment by Kowken** [comment]
> @Kowken what's the not lit up key? Next to the Right Shift? Is it next?
> 
> Seems like it correct?
> 
> The numkeys are already identified, I need your help for other things now. 
> 
> I haven't worked on the timings for the ambient mode to take effect so this is the wrong place.
> 
> Can you remember what was the LED ID for the "NEXT" in the media keys?
> 
> Trying to guess it should either be `120` or `121`.
> 
> Nvm I found your devicecontent from the ORGB discord.

Oh okay I get it now. Yeah I posted that on ORGB, do you still need something else ?

**Comment by Constrat** [comment]
I think I have everything.
- I've removed the debug from 4, 5, 6, 7
- Added the NEXT / SKIP key
- Renamed a NULL (LEDID 37) which is the Delete key for 15 inches

I think this is everything.

**Comment by Kowken** [comment]
> I think I have everything.
> 
> * I've removed the debug from 4, 5, 6, 7
> * Added the NEXT / SKIP key
> * Renamed a NULL (LEDID 37) which is the Delete key for 15 inches
> 
> I think this is everything.

Okay let me know if you need something else. Have a good day.

**Pull request merged**
