### PR TITLE
Support for TUF Gaming M5 Mouse.

### PR DESCRIPTION
**Pull request by IceStormNG**
Adds support for the TUF Gaming M5 Mouse (P304).

### CODE REVIEW

**Comment by seerge** [comment]
@IceStormNG thanks, i have squeezed this PR into https://github.com/seerge/g-helper/releases/tag/v0.128 :)

**Comment by SonamRinzinGurung** [comment]
Running into error while trying to use the TUF Gaming M5
image

**Comment by IceStormNG** [comment]
Can you please send the GHelper log and also open the "Details" and send that, too?

**Comment by SonamRinzinGurung** [comment]
************** Exception Text **************
System.ArgumentOutOfRangeException: InvalidArgument=Value of '1' is not valid for 'SelectedIndex'. (Parameter 'value')
Actual value was 1.
   at System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   at GHelper.AsusMouseSettings.VisualizeMouseSettings() in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 674
   at GHelper.AsusMouseSettings.RefreshMouseData() in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 470
   at GHelper.AsusMouseSettings..ctor(AsusMouse mouse) in C:\Users\Serge\g-helper\app\AsusMouseSettings.cs:line 111
   at GHelper.SettingsForm.ButtonPeripheral_Click(Object sender, EventArgs e) in C:\Users\Serge\g-helper\app\Settings.cs:line 1360
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

**Comment by IceStormNG** [comment]
I think I know what the issue is. How many profiles does the mouse have in Armoury Crate? 1, 3 or 5?

**Comment by SonamRinzinGurung** [comment]
I dont know, I've uninstalled it. But I do believe I had created some profiles before.

**Comment by IceStormNG** [comment]
[GHelper.zip](https://github.com/seerge/g-helper/files/12880150/GHelper.zip)

Please try this build. Apparently, the mouse has 3 Profiles and you're on Profile 2.

**Comment by SonamRinzinGurung** [comment]
Thanks it worked

**Comment by IceStormNG** [comment]
Ok. I will upload the fix.

**Pull request merged**
