### PR TITLE
Restore the miniled setting on reboot.

### LINKED ISSUE #2802: Mini-led setting doesn't appear to be re-applied after reboot
### Rules

- [X] I made myself familiar with the <a href='https://github.com/seerge/g-helper?tab=readme-ov-file'>Readme</a>, <a href='https://github.com/seerge/g-helper/wiki/FAQ'>FAQ</a> and <a href='https://github.com/seerge/g-helper/wiki/Troubleshooting'>Troubleshooting</a>.
- [X] I understand that, if insufficient information or no app logs will be provided, my issue will be closed without an answer.

### What's wrong?

When my machine boots, it appears to have 'forgotten' to disable the multi-zone backlight. If I cycle the backlight setting 3 times, everything seems to work perfectly afterwards.

### How to reproduce the bug?

1. Set G-Helper to autostart
2. Select 'One Zone' backlighting
3. Reboot the system
4. On reboot one of the multizone modes is clearly in use; I'm not sure if it's "Multi Zone" or "Multi Zone Strong" that it gets on reboot.
5. Change the backlight setting 3 times (to wrap back around to 'One Zone') and things work fine again.

### Logs

[log.txt](https://github.com/user-attachments/files/16077119/log.txt)
[config.json](https://github.com/user-attachments/files/16077126/config.json)

### Device and Model

Strix SCAR 18 G843JYR

### Additional information.

I also tried this on a 2023 Zepherus G14 which only has multi zone on or off and G-Helper seems to work perfectly there, so I'm not sure if this is a firmware problem or G-Helper not behaving the same way given that this model has multiple multi zone backlight modes.

### Armoury Crate

Uninstalled

### Asus Services

0

### Version

0.176.0

### OS

Windows 11 Version 23H2 (OS Build 22631.3737)

### PR DESCRIPTION
**Pull request by BillyONeal**
Fixes #2802

Appears to workaround firmware bug as described in https://github.com/seerge/g-helper/issues/2802

### CODE REVIEW

**Comment by BillyONeal** [comment]
Thanks for the nice logs, it made authoring a proposed patch to fix this very easy :)

**Comment by seerge** [comment]
@BillyONeal hello, thanks for PR. I see that you propose to force setting miniled status on every app start. 

I'm just not sure if all miniled devices reset their miniled status on reboot (cause otherwise it will be a lot of complains already)

I can propose to make this optional (i.e. force miniled command if some config parameter is set) ?

**Comment by BillyONeal** [comment]
> I can suggest to make this optional - i.e. force miniled command if some config parameter is set?

Sure! I just didn't want to file an issue without at least making an attempt to fix it, feel free to do/suggest anything else.

Forgive me, I've only really looked at this one .cs file, do you want to just read a different AppConfig value (as in, someone has to dig around in appdata to set it?) or do you want a checkbox on the 'Extra' page somehow?

Thanks for your consideration!

**Comment by BillyONeal** [comment]
Today I discovered an edge case this does not fix: If the machine boots with an external display connected, and the built in one is turned on later, it's still broken.

**Comment by BillyONeal** [comment]
OK, I made the behavior conditionally dependent on a new checkbox:

image

**Comment by BillyONeal** [comment]
Removed in favor of https://github.com/seerge/g-helper/commit/1c1cdf1bec654477ec5695b63b21e154b7b6135f

**Pull request closed without merging**
