### PR TITLE
Adding French and Português Version 

### PR DESCRIPTION
**Pull request by TomBonnot**
- French Version (needs some tweaks I guess so I will be working on it) 
- português (pt-br) version is undergoing, working on it with a Brazilian friend of mine. 

It is my first time doing a pull request and making a fork of a project, so do not hesitate to tell me if anything is wrong with it. 
I used JetBrains Rider and I think it did add some weird files, is it ok ?

### CODE REVIEW

**Comment by TomBonnot** [comment]
Okay so this is the .idea folder that JetBrains has added. Will remove it for my last commit. 
Sorry for the inconvenient

**Comment by seerge** [comment]
@TomBonnot thanks for contribution :), let me know when it will be final, so i can merge

**Comment by TomBonnot** [comment]
@seerge it is ready for review ! I let you merge it. Or tell me if anything is wrong ! Thank you

**Comment by seerge** [comment]
Great, thanks :) I'll include this in next release

**Pull request merged**
