### PR TITLE
Added support for ASUS TUF Gaming M4 Wireless (P306_Wireless) Mouse

### PR DESCRIPTION
**Pull request by IceStormNG**
TUF Gaming M4 Wireless (P306_Wireless) is now supported (thanks to @alexatthehub for testing and providing data) 
This also adds some general fixes for the mouse system. 
Battery is now only polled every 20s to reduce useless USB traffic, except for when the GHelper window opens. Then it is force-refreshed. Battery polling now happens in background thread to not block the UI.
Added better error handling when the mouse sends unexpected packets.

Some internal housekeeping to allow for easier crafting of new mouse classes with less redundant code.
Fixes the DPI colors on the buttons for mice that have no custom DPI colors in hardware.

### CODE REVIEW

**Comment by seerge** [comment]
@IceStormNG great, thanks a lot again for contribution.

How do you think, is this implementation stable enough to go "live" in a "latest release" state?

My current release strategy, is to once per last 3-4 releases make one "final" (as soon as it gathers ~ 1000 downloads from enthusiasts). This will push it to all remaining users via auto-update feature (as it checks only for "final" ones).

**Comment by IceStormNG** [comment]
I'm currently finalizing another mouse and RGB zoning. Not sure whether you want to wait for that but I will likely submit a pull request in a few hours for that.

As for stability. I run the latest build on my machine all the time and have fixed all bugs that I encountered. I guess there are not that many users with ASUS mice that are active here to submit bug reports.

I personally would like to add the Keris mouse and the RGB zoning before release if that is ok.

**Comment by seerge** [comment]
@IceStormNG i'm absolutely fine to wait :) 

+ I still want to fix this thing https://github.com/seerge/g-helper/issues/930 (need to wait for a user to respond)

When 103 will go live, i usually wait for a couple of days to gain ~ 1000 downloads or so ( unless someone spots a new issue there ) and then push it to autoupdate (otherwise windows defender may start flagging it if it )

**Comment by IceStormNG** [comment]
image


Btw. I made a new screenshot with the new zone buttons if you want to update that.

I'm waiting for one person to respond for testing the last changes to the Keris. Then you can release another version if you like to. The other mice will then come with a later version. There are already 2 new requests :D

**Comment by seerge** [comment]
@IceStormNG there is no rush with release :)

**Comment by IceStormNG** [comment]
That's good. Then I might also get the TUF M3 and the Strix Impact II Wireless also ready if the requestors tested and responded. :)

It's interesting. Some mice have more features in their firmware than AC lets you use. I enable those in GHelper as well if they work 😆

**Pull request merged**
