### PR TITLE
Update Program

### PR DESCRIPTION
**Pull request by Adam-S-Amir**
I love G-Helper but the built-in update button doesn't work, so this is a quick and dirty fix with bigger changes on the way.

### CODE REVIEW

**Comment by seerge** [comment]
@Adam-S-Amir hello, if you mean Auto Update prompt - it works :) what exactly doesn't work in your case?

I'm not a fan of creating separate executables, just to update

**Comment by Adam-S-Amir** [comment]
@seerge Hey! Yes, we can download the zip file, but it won't self-extract and replace the current version of G-Helper with the latest build. This goes for the auto update prompt and the download button in the bottom left-hand corner. A separate executable would be useful as it would solve these issues, and linking a button to said executable would (in my opinion) make this application more user-friendly/dummy proof. This task would be taken care of by me if given the opportunity, though merging my own changes are up to you. Again, I love this app; I wanted to fix a niche issue I had.

**Comment by seerge** [comment]
@Adam-S-Amir which version did you use to trigger auto update ? as in https://github.com/seerge/g-helper/releases/tag/v0.144 i have fixed an issue when it wouldn't extract if a folder with app contained special characters or spaces

So if you run 0.144 -> autoupdates should work (but there is no newer "final" release yet). It will trigger when i will mark new version as final :)

**Comment by seerge** [comment]
@Adam-S-Amir i have marked 0.146 as "final" release, so 0.144 (with auto-update fix) should now trigger update dialog :) please check if it works for you

**Comment by IceStormNG** [comment]
For me, the auto update did not work from 144 to 146. It closed and restarted, but started the old version again. I had to manually download the zip and replace GHelper

**Comment by seerge** [comment]
@IceStormNG it starts powershell process with unzip script inside
https://github.com/seerge/g-helper/blob/df35a576dfa772b3f99e3c669dee1e827cbdeabe/app/AutoUpdate/AutoUpdateControl.cs#L122C17-L122C17

Can you check ``log.txt`` for for actual command and just try to run it manually in powershell ? Would it work ?

**Comment by IceStormNG** [comment]
I guess I know what the issue is. My GHelper sits in "C:\Programs\GHelper". And when I run this manually, I get a "permission denied" when it tries to remove the old files.
Although, GHelper is running as admin, and should therefore not run into this issue. When I run the PS as admin, it does replace the files

**Comment by seerge** [comment]
@IceStormNG ah! I can then launch powershell with same permissions as parent process runs then.

**Comment by seerge** [comment]
@IceStormNG can you check if this build (with fake version 0.100) updates correctly in your conditions ?

[GHelper.zip](https://github.com/seerge/g-helper/files/13922782/GHelper.zip)

**Comment by IceStormNG** [comment]
Nope. Does not work. It downloads the file, and also removes the archive afterwards, but it does not replace the GHelper files.

**Comment by seerge** [comment]
@IceStormNG did you start it as admin ?

**Comment by IceStormNG** [comment]
I run it through task scheduler, and the flag "run with highest permission" is ticket.

**Comment by seerge** [comment]
@IceStormNG hm, I can't reproduce it now

I have placed test exe to ``C:\Program Files\GHelper`` (so system asked me for admin permissions even to create folder and copy it there)

Then if I run app as admin - it prompts for update - and auto updates
If I run it not as admin - it prompts for update and (expectedly) fails

I have already pushed this tweak to main https://github.com/seerge/g-helper/blob/527769042fc405354e2008fd25987727725a4c83/app/AutoUpdate/AutoUpdateControl.cs#L134

Mb you can tinker with that on your end, and try to figure out what prevents it from updating ?

**Comment by IceStormNG** [comment]
https://stackoverflow.com/questions/2532769/how-to-start-a-process-as-administrator-mode-in-c-sharp

It looks like newer .Net neeeds UseShellExecute Set to true for the runas to work. I might try that later.

**Comment by Kikimahe** [comment]
hi,

I had the same problem as @IceStormNG doing the updates : 

- Ghelper in this location: C:\Programs\GHelper
- Permission denied to save Zip file to this location.

I have tested the version above offered by Seerge.
Update works perfectly now.  👍

**Comment by IceStormNG** [comment]
Did some more testing. The reason is, that GHelper did not exit quickly enough so it gets a "permission denied" as windows does not allow deleting running exectuables. I will try to find out how to solve that.

**Comment by Kikimahe** [comment]
I don't think so because I tried this :
- Closing Ghelper
- Disabled task for Ghelper autostart
- Windows restart.

After restart, Windows still refuses to save Ghelper.zip to this location.

**Comment by IceStormNG** [comment]
For me it is. I just tested it by using "Wait-Process -Name" instead of sleep. GHelper does not terminate. If I then exit it via taskmanager, the update runs through.

**Comment by seerge** [comment]
@IceStormNG yeah, probably 1 second is not enough. Can you paste here full powershell command that you used instead ? or just do a PR with a tweak?

Thanks! :)

**Comment by IceStormNG** [comment]
> @IceStormNG yeah, probably 1 second is not enough. Can you paste here full powershell command that you used instead ? or just do a PR with a tweak?

I opened a PR with the two changes. It now works fine for me.

**Comment by seerge** [comment]
@IceStormNG merged :)

**Comment by Kikimahe** [comment]
It's fix. 

Even though I am an administrator, I had to modify the "user" permissions of the `C:\Program Files\GHelper `folder by checking "total control".

And now the automatic update happens by itself. ! \O/

Capture d'écran 2024-01-13 121615

**Comment by IceStormNG** [comment]
@Kikimahe  yeah, I also had to change permissions for that folder so that the regular user accounts can modifiy it. No big deal for me, although it should not be necessary.
For the admin to work, one has to set the "UseShellExecute = true" IIRC, but that makes the powershell window visible. And might scare some users xD

**Comment by seerge** [comment]
Oke, thanks everyone for cooperation. I'm closing this PR as it's not needed anymore :)

**Pull request closed without merging**
