### PR TITLE
Add groupboxes for backlight section & little PL translation fixes

### PR DESCRIPTION
**Pull request by tendan**
So I managed to change the appearance of backlight section to have groupboxes in it.

Now you are able to hide it with just hidding the groupbox instead of checkboxes and label manually.
I think there is an option for better styling configuration. Currently I don't know how to remove the border, but wanted to.
Hope my changes haven't brought spaghetti code nor bugs.

obraz

Also decided to change polish translation in this section of course.

I'm open to any feedback received.

Thanks!

### CODE REVIEW

**Comment by seerge** [comment]
@tendan hello,

Thanks for your contribution, but I think it would be better if you would ask about it first :) 

That section had groupboxes before, I have intentionally removed them in order to make it look cleaner in dark theme. Also for models with single zone (majority) it also hides "Keyboard" title completely in order to save space.

As for translations, they are being automatically coordinated via Crowdin https://github.com/seerge/g-helper/discussions/759
If you want you can join and offer your options there :)

**Comment by tendan** [comment]
Well, I didn't know I had to ask about these changes.
About hiding "Keyboard" title. I think it's good practice to tell user what they will operate on. On the first time, I've managed what I'm enabling/disabling after switching.
Maybe I'll found the way to remove these borders. Code with groupboxes looks cleaner.

**Comment by tendan** [comment]
I'll try to find the other container available in Windows Forms that doesn't affect appearance, but can simplify the code.

I think I can close this PR.

**Comment by seerge** [comment]
Closing as not planned for now :)

**Pull request closed without merging**
