### PR TITLE
Added option to switch between silent/balanced mode when on battery/plugged

### PR DESCRIPTION
**Pull request by Albert24GG**
I thought that a good addition to the other options would be to automatically switch to silent mode when running on battery, since this could have a positive impact on battery life. Something that can be improved is the placement of the checkbox, since I couldn't get it working without breaking the other objects around.
Screenshot 2023-02-20 234630

### CODE REVIEW

**Comment by seerge** [comment]
It's possible and I have thought about it before.But do people really need it ? 

Silent mode is NOT more economical than Balanced (unlike Eco GPU mode or low refresh rate), it's just more limited in terms of TDP, that's it. I easily get 6-7w battery drain on Balanced when do browsing or so.

My main concern here is not to overload app with too many options :D or I will have to do some extra settings page for them.

**Comment by Albert24GG** [comment]
Silent mode should also allow higher temperatures with no fans spinning, so that would help with battery drain a little in some scenarios.

**Comment by masi0** [comment]
> It's possible and I have thought about it before.But do people really need it ?
> 
> Silent mode is NOT more economical than Balanced (unlike Eco GPU mode or low refresh rate), it's just more limited in terms of TDP, that's it. I easily get 6-7w battery drain on Balanced when do browsing or so.
> 
> My main concern here is not to overload app with too many options :D or I will have to do some extra settings page for them.
> 
> Up to discussion :)

if auto profile switching = avoid additional application to be install then it could be a great and only alternative to armored crate!

**Comment by astronaut701** [comment]
Why not have an option to auto switch profiles that were selected when last plugged/last unplugged. Isn't that how Armory Crate does it?

**Comment by flemesre** [comment]
I think in this case it might make more sense to change the option to disabling CPU boost on battery for those who want it. Like @seerge said, the performance modes only really changes TDP, and I haven't noticed much difference in power draw between Silent and Balanced on my G15 2021. Disabling turbo boost, however, makes a big difference (~20W bursts to ~9W bursts) in peak CPU draw according to HWInfo64.

**Comment by yummypugs** [comment]
I just started using this app, and I would really appreciate an option like this. I like to use my laptop with 0 fans spinning when I'm in University and perhaps there is some battery saving to be found, as the computer is allowed to run hotter without spinning up fans.

**Comment by seerge** [comment]
But CPU boost checkbox is already in app ? So boost can be disabled? Or I'm not getting something

**Comment by flemesre** [comment]
> But CPU boost checkbox is already in app ? So boost can be disabled? Or I'm not getting something

I meant adding an option to disable the boost automatically when switching from plugged in to battery, similar to the GPU mode and refresh rate switched that are already implemented.

**Comment by seerge** [comment]
> > But CPU boost checkbox is already in app ? So boost can be disabled? Or I'm not getting something
> 
> I meant adding an option to disable the boost automatically when switching from plugged in to battery, similar to the GPU mode and refresh rate switches that are already implemented.

CPU Boost is part of windows power plan, and it's aready 2 separate settings for on / off battery

https://imgur.com/a/ZaAoGPB

**Comment by ke1ne** [comment]
> It's possible and I have thought about it before.But do people really need it ?

Yeap, this could be nice.

**Comment by seerge** [comment]
this feature is already implemented, app remembers states on battery/power

**Comment by seerge** [comment]
Sorry, for closing a pull request btw, i thought that I'm answering to an issue. But anyway, current logic of performance modes is different - as app remembers them per battery/power state, so switch is not needed :)

**Comment by Albert24GG** [comment]
> Sorry, for closing a pull request btw, i thought that I'm answering to an issue. But anyway, current logic of performance modes is different - as app remembers them per battery/power state, so switch is not needed :)

No problem!:) It's nice you implemented a solution for that.

**Pull request closed without merging**
