### PR TITLE
it should be FA506IC

### PR DESCRIPTION
**Pull request by aliazhar-id**

### CODE REVIEW

**Comment by seerge** [comment]
@aliazhar-id hello, do i understand correctly that this is related to https://github.com/seerge/g-helper/issues/1413 ?

**Comment by aliazhar-id** [comment]
> @aliazhar-id hello, do i understand correctly that this is related to #1413 ?

So actually my laptop model is FA506IC, not FX506IC. and also I searched on the Asus website and there was no FX506IC(cmiiw) model.

**Comment by seerge** [comment]
@aliazhar-id actually [FX506IC](https://tweakers.net/pricewatch/1760650/asus-tuf-gaming-a15-fx506ic-hn021w.html) is also a valid model , so I just added yours to the list as well https://github.com/seerge/g-helper/commit/fc83e0e8249d6effb085701b0fb16aa44dceead2 :)

[GHelper.zip](https://github.com/seerge/g-helper/files/12897999/GHelper.zip)

So this build should act correctly for brightness in your case

**Comment by aliazhar-id** [comment]
Okay. thank you then. Sorry to bother you.

Lastly, could you add the **FX506LHB** too

**Comment by seerge** [comment]
@aliazhar-id ``FX506LHB`` is already covered by ``ContainsModel("FX506LH");`` :)

**Pull request closed without merging**
