### PR TITLE
Added Rog Strix Impact II Wireless mouse support. 

### PR DESCRIPTION
**Pull request by IceStormNG**
Added support for the Strix Impact II Wireless mouse.

Hint: has the same DPI switching problem as the Keris Wireless has.

### CODE REVIEW

**Comment by IceStormNG** [comment]
Btw. You might want to update the discussion message whenever I add a mouse so people know which is supported. The discussion will get out of hand very soon and it will be impossible to find out what mouse is supported and which is not.

**Comment by seerge** [comment]
@IceStormNG great! thanks again.

I have updated main discussion with a list https://github.com/seerge/g-helper/discussions/900

But I think this PR will go to v.104 already

**Comment by IceStormNG** [comment]
Alright. I have the TUF M3 almost ready as soon as I get the response.
Then I can work on the Gladius III (non-wireless).

**Comment by seerge** [comment]
@IceStormNG I can order some Asus mouse from amazon probably, so i can at least test this section w/o any "hacks" in a code. Which one from popular ones is missing?

**Comment by IceStormNG** [comment]
I guess the most popular ones are already included. The Gladius III Wireless and the Chakram X.

The Keris  and the Spartha X seem to be popular. The Keris wireless is supported already. The Spartha also has a dock that can be RGB lit (lmao). But it is rather pricey.
The ROG Carry is missing but it is in progress. I also implemented 2 TUF Mice (M3 and M4 Wireless). M3 is almost ready, M4 is already merged.

Going by Amazon sales, the ROG Puggio II wireless and the Harpe Ace seem to be popular and they're both missing. The Harpe Ace is quite expensive.

**Comment by seerge** [comment]
@IceStormNG i was looking into  Harpe Ace as it seem to be most similar to my Logitech Pro Superlight ... (but it costs like a lot)

**Comment by IceStormNG** [comment]
Yeah. the "better" ROG mice are ... pricey. My Chakram X was also quite an investment to say it lightly. For a mouse.

**Comment by IceStormNG** [comment]
People already request keyboards and headsets.... I might have to get one into my hands at some point to log the packet traffic from Armoury Crate.
At least for one full-featured model. The others can then be derived from that.

**Comment by AudreyAP** [comment]
If I can get my hands on a Harpe Ace would it be possible for you to build compatibility for it remotely? I can provide dumps, etc.

**Comment by IceStormNG** [comment]
> If I can get my hands on a Harpe Ace would it be possible for you to build compatibility for it remotely? I can provide dumps, etc.
> 
> Edit: Just saw that someone is already helping with it in a discussion. Search didn't show it for some reason.

Well, yeah. But we're currently struggling to get the OMNI receiver to work. That thing apparently needs some initialization. I hope the user can capture that. Otherwise it will be next to impossible to "guess" it.

**Pull request merged**
