### PR TITLE
Ambient + Custom colors effect for ROG Strix

### PR DESCRIPTION
**Pull request by DLdota**
https://github.com/seerge/g-helper/assets/10529536/1155273d-7e84-48ac-a1d9-11984e89f712

Ambient effect use ~ 0.4% CPU.

I also rewrote USB.cs cuz it was mess

### CODE REVIEW

**Comment by seerge** [comment]
@DLdota hello, thanks for PR, that's quite a lot of changes!

Honestly, the main reason I didn't add "ambient" RGB (or literally coloring keyboard into average or dominant color of the screen) is performance cost for that

You seem to have a powerful CPU, but when I try that on my G14 I get like 4-5% CPU usage constantly (which is really a lot)

Screenshot 2023-11-10 141925

I don't mind to merge it, but then it will have to be a veeery big asterisk that it will hamper performance significantly :|

**Comment by seerge** [comment]
@DLdota so, I decided to dig into performance issues a bit more. 

And it looks like screenshotting / measuring color is not the only thing that takes resources. 

It is also a ``HidLibrary`` and whole USB communication itself. As with 80ms refresh time, even **HeatMap** mode (that you called "Heap" in your changes) also was taking 1-2% of CPU (which is still unacceptable) 

I have migrated everything to ``HidSharp`` library instead, as it was already used for **AnimeMatrix** module (inherited from original implementation ) and it performs way better.

I have also did a split of ``AsusUSB`` into few separate classes, similar to what you did

It's already merged into main https://github.com/seerge/g-helper/commit/5c4500315cf4233c25cf7f8ea4143a788d448041

I may still look for faster / less taxing methods to do screenshots and measure colors, may be we can pull something out here actually.

**Comment by DLdota** [comment]
@seerge Nice work! 
HidDevice.Write is really strangely increased execution time by 40%.

And the current method can be optimized 2-3 times using STRETCH_DELETESCANS to get  screen with a small resolution (300 or 400) pixels and then resize it qualitatively to 4x2.
I think the average CPU usage will be around 0.1% or less.

**Comment by seerge** [comment]
@DLdota ok, good.

If you want - you can try to update your PR to match current implementation + use even lower screenshot resolution as you mentioned. 

If you don't - let me know , and I will try to come up with something by myself

I have quickly looked into alternative ways to make screenshot using DirectX, but it requires including bunch of extra libraries in the app, and therefore increases total size by a lot. And I'm trying to avoid it atm.

**Comment by DLdota** [comment]
Reduced CPU load to 0.15% (checked via ProcessHacker)

**Comment by seerge** [comment]
@DLdota cool, but can you migrate your additions into current state of main branch (that uses ``HidSharp`` ) ? :)

**Comment by DLdota** [comment]
Done!

**Comment by seerge** [comment]
@DLdota good! this time it consumes something between 0.1-0.2 on 1600p display and 0.3% when 4k monitor is set as main in my case :) that will work.

Merging then

**Comment by D9r31Y05** [comment]
When I set ambient mode on ROG STRIX G533ZW not all the keys all lighting up. The ones that are lighted up work fine in ambient mode and function as supposed. But the ones not working stays off all the time. When I switch to other lighting mode, all the keys are working fine.

**Comment by seerge** [comment]
@D9r31Y05 can you post a photo of your keyboard?

How does Heatmap mode look on your device?

**Comment by D9r31Y05** [comment]
HEATMAP HEATMAP
AMBIENT AMBIENT

**Comment by seerge** [comment]
@DLdota I think that light zones that you used at https://github.com/seerge/g-helper/blob/96cbcbaf7fc291fe64059994c78fb2e14565352c/app/USB/Aura.cs#L522 

Don't match with devices that support per-key RGB (as then each zone = 1 key, not a real "zone")

As far as I remember OpenRGB has separate protocol, to set backlight per real zone, not key. Do you mind to check that ? :)

I can't test anything of that as I simply don't own a Strix device.

**Comment by seerge** [comment]
@D9r31Y05 can you check OpenRGB app and test if it allows you to set RGB colors there per Zone (not per key!) and if works for you there ?

Your keyboard is technically divided into 4 vertical zones. And each can  light up all together instead of lighting up individually key by key.

**Comment by D9r31Y05** [comment]
@seerge I will check this out today and report back.

**Comment by D9r31Y05** [comment]
@seerge I tried OpenRGB app.

The only setting in the drop down menu zone working to change the color of the laptop and keyboard is all zones or keyboard zone. Lightbar or lid doesn't do anything at all. I can change color per key in the keyboard zone but nothing else. To change lid or logo or lightbar I have to change everything at the same time in keyboard or all zones. As you can see in the last 2 pictures I put the keyboard in purple and the lid and lightbar in green and blue but no change registered.

Screenshot 2023-11-18 150546
Screenshot 2023-11-18 150642
Screenshot 2023-11-18 150700
Screenshot 2023-11-18 151031

**Comment by seerge** [comment]
@D9r31Y05 oke, clear. Then it could be difficult to properly do multiple colors backlight for ambient mode on your device. As you need to send correct colors not to 4 zones, but to each button individually, and consider it's actual (physical) location on keyboard :) For me - it's almost unrealistic to do (as i don't even have a strix model), may be someone else can contribute

I can offer a "temporary" solution - to color whole keyboard into 1 average screen color. Same as G-Helper does now for all models w/o per-key RGB (like Zephyrus or Flow).

**Comment by seerge** [comment]
@D9r31Y05 check this build

[GHelper.zip](https://github.com/seerge/g-helper/files/13401432/GHelper.zip)

**Comment by D9r31Y05** [comment]
@seerge Tried it and same behavior. Some keys stay off no matter what is on the screen.

**Comment by D9r31Y05** [comment]
@seerge I tried the ambient effect added in OpenRGB with effect plugin. It is working as it should. Sampling my screen and using screen copy. All my keys and laptop zones are lighting up correctly and reacting to what is shown on the screen. The effect is getting applied per key. I think @DLdota is a contributor to the ambient effect in the OpenRGB plugin.

**Comment by seerge** [comment]
@D9r31Y05 can you quickly check this build ? It should be only a single-zone Ambient, but I want to check if my attempt to set all RGB per key works ?

[GHelper.zip](https://github.com/seerge/g-helper/files/13404297/GHelper.zip)

**Comment by D9r31Y05** [comment]
@seerge Tried it and all the zones and keys are the same ambient color reacting to the screen.  It works like you want.

**Comment by DLdota** [comment]
it's a lottery without information about led indexes.
anyway you can try [https://mega.nz/file/sdxEGaTZ#Xzg3e98RP6-IJyQiQjCpIYZHY6fSInFT3e_dUnISqCU](url)

> As far as I remember OpenRGB has separate protocol, to set backlight per real zone, not key. Do you mind to check that ? :)
> 
> I can't test anything of that as I simply don't own a Strix device.

almost the same. but It’s not clear which button corresponds to which led index.

**Comment by seerge** [comment]
@DLdota @D9r31Y05 the indexes are actually known (from openrgb) 

I have moved them, but I know need to group keys into something like 4 zones ....

https://github.com/seerge/g-helper/blob/b6fe7c9ddfa7ea304388a7651e713be9b3925baa/app/USB/Aura.cs#L361 :)

**Comment by DLdota** [comment]
> @DLdota @D9r31Y05 the indexes are actually known (from openrgb)
> 
> I have moved them, but I know need to group keys into something like 4 zones ....
> 
> https://github.com/seerge/g-helper/blob/b6fe7c9ddfa7ea304388a7651e713be9b3925baa/app/USB/Aura.cs#L361
> 
> :)
I dont think they are correct, cuz the screenshot shows that the lightbar zone didnt change color to green.
anyway i if I guessed right with indexes, then everything should work, and each button will have a unique color, if not, then Im afraid it may take 50 or 100 attempts, too much for me :(

**Comment by seerge** [comment]
@DLdota which screenshot ?

I took indexes from here https://gitlab.com/CalcProgrammer1/OpenRGB/-/blob/master/Controllers/AsusAuraCoreController/AsusAuraCoreLaptopController.cpp

**Comment by seerge** [comment]
@D9r31Y05 can you try this build and check if zones work ?

[GHelper.zip](https://github.com/seerge/g-helper/files/13404582/GHelper.zip)

**Comment by D9r31Y05** [comment]
@seerge Yes I can clearly see different laptop lighting zones reacting to different color in my screen.

**Comment by seerge** [comment]
@D9r31Y05 mind posting a couple of photos ? As I have created those zones by simply assigning each key manually. So I'm not sure if it looks ok ... 

@DLdota question to you - does latest build (also updated main branch) look ok on your device with no per-key RGB ?

**Comment by D9r31Y05** [comment]
@seerge I am not able to test and post photo right now. I'll be able tomorrow. Sorry for the delay.

**Comment by DLdota** [comment]
> @D9r31Y05 mind posting a couple of photos ? As I have created those zones by simply assigning each key manually. So I'm not sure if it looks ok ...
> 
> @DLdota question to you - does latest build (also updated main branch) look ok on your device with no per-key RGB ?

broken, but i can fix it

**Comment by seerge** [comment]
@DLdota well, i assume for your case led layout is just different (much less zones) :) if you can tweak it to also work for you that would be cool.

As per-key zones seem to work ok (just confirmed it in another issue) https://github.com/seerge/g-helper/issues/1615#issuecomment-1817994209 

I think your model is one of those https://github.com/seerge/g-helper/blob/fad7396c8f0e62d32e2fcbc22961809e49a18cc9/app/AppConfig.cs#L356 ? You can probably add a switch then

**Comment by DLdota** [comment]
> @DLdota well, i assume for your case led layout is just different (much less zones) :) if you can tweak it to also work for you that would be cool.
> 
> As per-key zones seem to work ok (just confirmed it in another issue) [#1615 (comment)](https://github.com/seerge/g-helper/issues/1615#issuecomment-1817994209)
> 
> I think your model is one of those
> 
> https://github.com/seerge/g-helper/blob/fad7396c8f0e62d32e2fcbc22961809e49a18cc9/app/AppConfig.cs#L356
> 
> ? You can probably add a switch then

yes, very soon

**Comment by D9r31Y05** [comment]
@seerge Here are the screenshot of the zone reacting to the screen.

**Comment by D9r31Y05** [comment]
@seerge Here is a video of the ambient effect with zone with G-Helper.

https://github.com/seerge/g-helper/assets/151216809/3575e7b1-05e7-4316-a220-152499a6c230

Here is the same video but with the ambient effect from Open RGB ambient effect.

https://github.com/seerge/g-helper/assets/151216809/f617984b-b7d2-4f48-b7e4-75cd0d7a65c7

**Comment by seerge** [comment]
Great, looks ok as for me

**Comment by D9r31Y05** [comment]
Yes thank you for fixing it!

**Comment by HaziqBD** [comment]
Just saying it here. I use a laptop with an extra monitor. The ambient mode uses the point of contact between my laptop screen and monitor. Basically where the edge of screen meet. Is it intended like that?

**Comment by seerge** [comment]
@HaziqBD ambient mode makes a screenshot of your main display (in windows), and then sets keyboard to average color of whole screen

**Comment by HaziqBD** [comment]
@seerge ouh ok. Been wondering how it works. Thanks for the info

**Comment by lucidnx** [comment]
Hello! It seems to be not working properly on G14 2022. Whole keyboard is white (1zone keyboard, that's okay), but it does not change colors, only intensity of white.

**Comment by DLdota** [comment]
> Hello! It seems to be not working properly on G14 2022. Whole keyboard is white (1zone keyboard, that's okay), but it does not change colors, only intensity of white. // EDIT, my bad, when trying fullscreen color, it works. maybe there should be function to pick most saturated colors from screen or gnore blacks/whites until it's covering 80% of screen, instead of mixing all together? keyboard stays most of time in black-to-white range. It's clear that it's not really made for 1 zone keyboards.

yes ur right, Due to excessive rapid compression, the black color eats other colors. need to do the compression like the 4-zone method and it will be noticeably better. i will make PR.

**Comment by seerge** [comment]
@lucidnx try build from @DLdota 's [PR](https://github.com/seerge/g-helper/pull/1635)

[GHelper.zip](https://github.com/seerge/g-helper/files/13443923/GHelper.zip)

**Pull request merged**
