### PR TITLE
Clamshell power user settings

### PR DESCRIPTION
**Pull request by IceStormNG**
This allows users to set their lid default action when clamshell is not engaged.

Set `clamshell_default_lid_action` in config.json to any of those values.

0 = Do nothing
1 = Sleep (default)
2 = Hibernate
3 = Shutdown

### CODE REVIEW

**Comment by seerge** [comment]
Does it make sense to manually set this variable on check of "auto clamshell" if existing state is at least Hibernate? I really doubt someone would accidentally have that setting

**Comment by IceStormNG** [comment]
We could do that if you want to. So, if the value is 2 or 3 we save it if the option does not exist yet in the config.json.

**Comment by seerge** [comment]
My point here is to keep app non invasive as possible:)

**Comment by IceStormNG** [comment]
Ok. I added code to read and save the setting on startup of ghelper if it is either hibernate or shutdown.
Sleep will not be saved as it is the default if uncofigured.
If it is set to "Do nothing" it is assumed that it was set by GHelper. If the user did that themselves, they shouldn't use the clamshell mode toggle.

**Comment by seerge** [comment]
@IceStormNG great, thanks!

**Pull request merged**
