### PR TITLE
Fan calibration

### PR DESCRIPTION
**Pull request by seerge**
Added a button to "Calibrate" Fan Axis (i.e. measure maximum RPM) for each fan, and adjust axis accordingly.

Actual fan behavior isn't affected anyhow, as it's set in %

### CODE REVIEW

**Comment by ke1ne** [comment]
Cool stuff! I would add some warning, like "This will drive your fans to the maximum speed! Also, can be loud."
Also, the CANCEL button with smooth slowing down could be grate too.
Thank you!

**Comment by seerge** [comment]
@ke1ne well, not louder than Turbo in most cases :)

Setting any mode will "cancel" that (as it will set original fan curve back)

But app will do that when calibration is finished anyway (i.e. when it will see that fan speed is not raising anymore)

**Comment by ke1ne** [comment]
@seerge I never got those speeds before, even with Turbo and active gaming. It feeled almost almost like "fans are gonna break" (6000+ rpm).

**Comment by seerge** [comment]
@ke1ne lucky you. It just sets 100% fan curve, that's it :) it won't break anything

**Comment by ke1ne** [comment]
@seerge OK, got it. Thanks!

**Comment by seerge** [comment]
@tdj88 currently ``Calibrate`` button appears for device where it's possible to read default fan curve. Both G14 and G16 2024 just respond with zeroes instead of one, so app assumes that's not supported and hides a button :)

The only thing Calibrate feature does - it sets custom fan curve with all dots at 100% and then waits until fan speed stops at some value, to remember it adjust Y-axis on a chart with maximum recorded RPM. But same happens if app just spots higher RPM during normal operation. It remembers that.

Problem is that both G14/G16 2024 have insanely slow reaction speed on fans, it took me like 2 minutes until fans reached their max RPM.

What you can do - is set curve to 100% manually and just write me your maximum values. I can hardcode them as defaults for your model  here
https://github.com/seerge/g-helper/blob/300eb7af7027df4030c568fea63f0cb4d2372044/app/Fan/FanSensorControl.cs#L46

**Comment by tdj88** [comment]
@seerge 
CPU MAX SPEED= 6100 RPM (goes between 6100 and 6200)
GPU MAX SPEED= 6100 RPM (goes between 6100 and 6200)
MID FAN MAX SPEED = 9200 RPM

**Comment by seerge** [comment]
@tdj88 ok, great. Is it based on Turbo mode under the hood ?

**Comment by tdj88** [comment]
@seerge I just did balance  underhood for max fan speed

**Comment by seerge** [comment]
@tdj88 can you check if it's same with Turbo?

**Comment by tdj88** [comment]
@seerge Same speeds in Turbo  (Note: Mid fan went up to 9300  for  restricted  airflow, lifting the laptop is drops to 9100 to 9200 RPM)

**Comment by seerge** [comment]
@tdj88 ok, added

This build should show calibrated values from start

[GHelper.zip](https://github.com/seerge/g-helper/files/14998301/GHelper.zip)

**Pull request merged**
