### PR TITLE
Support for ROG Harpe Ace Aim Lab Edition (P713).

### PR DESCRIPTION
**Pull request by IceStormNG**
Mouse support for the ROG Harpe Ace Aim Lab Edition (P713). Mouse is supported wired, via wireless dongle and also through an OMNI Receiver.

### CODE REVIEW

**Comment by seerge** [comment]
@IceStormNG great! Congrats on finishing it.

What was the main reason it didn’t work? A custom packet size?

**Comment by IceStormNG** [comment]
Thanks

Yes and also something else. Yes, normally the mouse wants 64bytes packets (+1 for the report id). But through the omni receiver it only wants 63 bytes (+ 1 for the report id, which is not 0 here, like for all other mice, but 3).
And: it has multiple sub devices. Only one of them has the report id 3 and support interrupt write and read, which is the one that talks to the mouse.

**Comment by seerge** [comment]
@IceStormNG i see, XGM has a similar trick, it wants 300 bytes of data as it seems

And it’s indeed unrealistic to catch all that w/o device :)

**Comment by IceStormNG** [comment]
Yeah. I hope I don't have to "abuse" amazon return policy more often or they might not like that. Most mice got implemented without trickery, though I could use one of the mice where the DPI switch doesn't work. I guess they send the DPI switch command through another device endpoint or with a different report ID.

**Pull request merged**
